= Troubleshooting FORWARD nodes' connection to the master servers in Security Onion 

sosetup only sets up autossh rules when setting up 'Elastic Stack', choose the 'Elastic Stack' option when setting up a FORWARD node to send bro logs through syslog-ng

== Script `/usr/sbin/sosetup` symlinked to `/usr/sbin/sosetup-elastic`

When using a GUI to copy the ssh key from the sensor to the master, the following command is used:

 $ xfce4-terminal -x sudo -i ssh-copy-id -i "$KEY".pub $SSH_USERNAME@$SERVERNAME

The PRIVATE KEY (not sent to the master, but used to authenticate from the sensor to the master) is `/root/.ssh/securityonion`

The PUBLIC KEY (sent to the master and stored on the MASTER at `/home/USER/.ssh/authorized_keys`) is `/root/.ssh/securityonion.pub`

Both the PUBLIC (`.pub`) and PRIVATE key (no extension) are generated by the command

 $ ssh-keygen -f "$KEY" -N '' >> $LOG 2>&1  

== `sosetup-elastic` Configuring firewall rules on the master

The `sosetup` script opens up the following ports

You may need to run `so-allow` on the MASTER and choose the `f` option to forward TCP port 6050 to the docker container. I'm not sure if this is configured in `so-setup` as of now.

----
# Copy the script over
scp -i "$KEY" $SOSETUPSCP $SSH_USERNAME@$SERVERNAME:$SOSETUPSCP >> $LOG 2>&1 

# Run the script on the master server using sudo
if [ "$OUTPUT" = "gui" ]; then 
    xfce4-terminal -x ssh -i "$KEY" -t $SSH_USERNAME@$SERVERNAME sudo /bin/bash $SOSETUPSCP
fi
----

== Viewing processes that are attached to ports

From the below output, the `ss` command must be run as the `root` user or with `sudo` to see programs that are attached to ports.

----
root@test1:/home/user# ss -anotp | grep 6050
LISTEN     0      128               127.0.0.1:6050                     *:*      users:(("ssh",28516,5))
ESTAB      0      0                 127.0.0.1:6050             127.0.0.1:33095  users:(("ssh",28516,6))
ESTAB      0      0                 127.0.0.1:33095            127.0.0.1:6050   timer:(keepalive,99min,0) users:(("syslog-ng",23242,21))
LISTEN     0      128                     ::1:6050                    :::*      users:(("ssh",28516,4))
root@test1:/home/user# exit
exit

user@test1:~$ ss -anotp | grep 6050
LISTEN     0      128               127.0.0.1:6050                     *:*     
ESTAB      0      0                 127.0.0.1:6050             127.0.0.1:33095 
ESTAB      0      0                 127.0.0.1:33095            127.0.0.1:6050   timer:(keepalive,99min,0)
LISTEN     0      128                     ::1:6050                    :::*     

user@test1:~$ sudo ss -anotp | grep 6050
LISTEN     0      128               127.0.0.1:6050                     *:*      users:(("ssh",28516,5))
ESTAB      0      0                 127.0.0.1:6050             127.0.0.1:33095  users:(("ssh",28516,6))
ESTAB      0      0                 127.0.0.1:33095            127.0.0.1:6050   timer:(keepalive,99min,0) users:(("syslog-ng",23242,21))
LISTEN     0      128                     ::1:6050                    :::*      users:(("ssh",28516,4))
----




Note that the typical key path is `/root/.ssh/securityonion` and the script appends `.pub` to that file when copying it

== Notes on sosetup script

== working with zenity

The progress bar is displayed by a program named `zenity`. This program will take input from STDIN (when the `CONFIGURE_SERVICES` function is executed) and update the percentage bar and the text.

NOTE: To update the text, there must be a `#` as the first character of the string (ex: `echo "# UPDATE THE TEXT ON THE DIALOG"`)

If you pass a number to zenity through STDIN, the progress bar will be updated to that position (from 0-100).



== Restarting autossh

I was using the command to stop autossh 

 $ kill -SIGINT `pgrep autossh`

This command didn't seem to stop autossh

I was able to stop it using 

 $ kill -9 `pgrep autossh`

Is the `-SIGINT` parameter the right choice?

/etc/logstash/conf.d/LOGSTASH CONFIGS

syslog-ng is configured in the 0000_syslogng.conf file
tcp port 6050

Goes through an autossh tunnel




== How to get bro logs? And only bro logs



== API commands for elasticsearch


Press `CTRL+Enter` to execute a command when the cursor is over it

`get _cat` - list all `cat` commands

`get _cat/shards?v` - pring out the shards with headers

`cat` commands can take the parameters `v`, `h`, and `help`. 

`v` - print headers

ex: `get _cat/index?v`

`h` - select columns by column name

ex: `get _cat/shards?h=id`

`help` - print out info about the columns

ex: `get _cat/shards?help`
