= Troubleshooting FORWARD nodes' connection to the master servers in Security Onion 

sosetup only sets up autossh rules when setting up 'Elastic Stack', choose the 'Elastic Stack' option when setting up a FORWARD node to send bro logs through syslog-ng

== Script `/usr/sbin/sosetup` symlinked to `/usr/sbin/sosetup-elastic`

When using a GUI to copy the ssh key from the sensor to the master, the following command is used:

 $ xfce4-terminal -x sudo -i ssh-copy-id -i "$KEY".pub $SSH_USERNAME@$SERVERNAME

The PRIVATE KEY (not sent to the master, but used to authenticate from the sensor to the master) is `/root/.ssh/securityonion`

The PUBLIC KEY (sent to the master and stored on the MASTER at `/home/USER/.ssh/authorized_keys`) is `/root/.ssh/securityonion.pub`

Both the PUBLIC (`.pub`) and PRIVATE key (no extension) are generated by the command

 $ ssh-keygen -f "$KEY" -N '' >> $LOG 2>&1  


== `sosetup-elastic` Configuring firewall rules on the master

The `sosetup` script opens up the following ports

You may need to run `so-allow` on the MASTER and choose the `f` option to forward TCP port 6050 to the docker container. I'm not sure if this is configured in `so-setup` as of now.

----
# Copy the script over
scp -i "$KEY" $SOSETUPSCP $SSH_USERNAME@$SERVERNAME:$SOSETUPSCP >> $LOG 2>&1 

# Run the script on the master server using sudo
if [ "$OUTPUT" = "gui" ]; then 
    xfce4-terminal -x ssh -i "$KEY" -t $SSH_USERNAME@$SERVERNAME sudo /bin/bash $SOSETUPSCP
fi
----


== Debugging ssh tunnel issues

* Check that `so-autossh-restart` actually restarted the `autossh` process
** may need to run `kill -SIGKILL `pgrep autossh` and then `so-autossh-start`
* Check that `/root/.ssh/securityonion_ssh.conf` has `AUTOSSH_OPTIONS` for local port forwarding (6050 for syslog-ng)
* Check that `autossh` is running
** `ps -ef | grep autossh`
* Check that the local port (6050) is listening
** `sudo ss -anotp | grep 6050`
* Commands that can be used to interact with `authssh`:
** `so-autossh-start` / `stop` / `restart` / `status`
* Check that the iptables rules are set up on the master
** To check, run `so-allow-view` there should be rules in IPTABLES with `docker` in the rule and port 6050
** If you need to add them, run `so-allow` and choose the `f` option to add a forwarder
* Verify that the sensor can ssh into the master
** If not, check that the sensor's public key is stored in the master's `authorized_keys` file
** On the master at `/home/USER/.ssh/authorized_keys` the file from the sensor at `/root/.ssh/securityonion.pub` should be an entry

== Viewing processes that are attached to ports

From the below output, the `ss` command must be run as the `root` user or with `sudo` to see programs that are attached to ports.

----
root@test1:/home/user# ss -anotp | grep 6050
LISTEN     0      128               127.0.0.1:6050                     *:*      users:(("ssh",28516,5))
ESTAB      0      0                 127.0.0.1:6050             127.0.0.1:33095  users:(("ssh",28516,6))
ESTAB      0      0                 127.0.0.1:33095            127.0.0.1:6050   timer:(keepalive,99min,0) users:(("syslog-ng",23242,21))
LISTEN     0      128                     ::1:6050                    :::*      users:(("ssh",28516,4))
root@test1:/home/user# exit
exit

user@test1:~$ ss -anotp | grep 6050
LISTEN     0      128               127.0.0.1:6050                     *:*     
ESTAB      0      0                 127.0.0.1:6050             127.0.0.1:33095 
ESTAB      0      0                 127.0.0.1:33095            127.0.0.1:6050   timer:(keepalive,99min,0)
LISTEN     0      128                     ::1:6050                    :::*     

user@test1:~$ sudo ss -anotp | grep 6050
LISTEN     0      128               127.0.0.1:6050                     *:*      users:(("ssh",28516,5))
ESTAB      0      0                 127.0.0.1:6050             127.0.0.1:33095  users:(("ssh",28516,6))
ESTAB      0      0                 127.0.0.1:33095            127.0.0.1:6050   timer:(keepalive,99min,0) users:(("syslog-ng",23242,21))
LISTEN     0      128                     ::1:6050                    :::*      users:(("ssh",28516,4))
----




Note that the typical key path is `/root/.ssh/securityonion` and the script appends `.pub` to that file when copying it

== Restarting autossh

I was using the command to stop autossh 

 $ kill -SIGINT `pgrep autossh`

This command didn't seem to stop autossh

I was able to stop it using 

 $ kill -9 `pgrep autossh`

Is the `-SIGINT` parameter the right choice?

/etc/logstash/conf.d/LOGSTASH CONFIGS

syslog-ng is configured in the 0000_syslogng.conf file
tcp port 6050

Goes through an autossh tunnel

