= Configure a Windows Server 2012R2 Machine
Steve Willson 1/11/18

The walkthrough goes through how to set up a Windows Server 2012R2 machine to be a Domain Controller for a lab setup

== Download Images

Download the evaluation copy of Windows Server 2012R2 from: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012-r2

I chose to download the ISO version.

== Set up on VMware

Open VMware and select `New Virtual Machine...`

Choose the downloaded ISO and select the appropriate options to install Windows Server 2012R2.

Once Windows installs, you will be prompted to enter a password for the Administrator User.


== Configure Windows as a Domain Controller

* In the `Server Manager > Dashboard` select `Manage` in the upper right corner
* Select `Add Roles and Features`
** The `Add Roles and Features Wizard` will appear
* At `Before You Begin` click `Next`
* At `Installation Type` select `Role-based or feature-based installation` and click `Next`
* At `Server Selection` select `Select a server from the server pool` and click `Next`
* At `Server Roles` leave the defaults selected and select the following additional options
** `Active Directory Domain Services`
** `DNS Server`
** `Network Policy and Access Services` 
* At `DNS Server` click `Next`
* At `AD DS` click `Next`
* At `Network Policy and Access Services` click `Next`
* At `Role Services` leave `Network Policy Server` selecdted and click `Next`
* At `Confirmation` click `Install`

The server will take a few minutes to install the selected options.




