= gen_blog README 
Steve Willson 5/7/18

== Requirements for gen_blog.sh

=== Main page (index.html) 

* Ability to set a heading, each adoc page should link back to the main page?
* Configure 'contact me' information (github, twitter, email, website)

=== Design

* Clean look, white text on a black background
* Each entry will have a Title, author, date, time to read, text (5? lines of text will be shown on the main page)
* Each entry will have a link back to the main page
* Links to other pages in the blog, arrange the content by date (reverse with newest entries on top)
* Metadata tags for blog entries?

* Don't care about view statistics, running javascript, just display asciidoc formatted pages right now

Display asciidoc files on a static webpage

=== Setup

Treat the generation of the blog as something that can be auto-deployed from a github repo

* Setup a webserver
* Generate a keypair `ssh-keygen`
* Copy the public key to github (or similar git hosting site)
* Set up a cron job for the webserver to check in with the git server using ssh (hourly?), copy files that have changed to a specified directory (`~/blog`?) and then use asciidoctor and a bash script to generate the content and write the content to `/var/www/html/`


=== Home Page generation

Generate the header
Generate the 'contact me' area
Select the first 10 lines of each of the adoc files (reverse sorted by date)

Set the following parameters
BLOG_TITLE, BLOG_SUBTITLE, TWITTER, WEBSITE, GITHUB, EMAIL


