:stylesheet: ./boot-cyborg.css
= Bro Monitoring

Visit website at http://try.bro.org/#/trybro

Bro is event driven, you can control any action by making it event driven.

two events always raised

* bro_init()
* bro_done()

Bro log files
https://www.bro.org/sphinx/script-reference/log-files.html

Bro can load a script from other programming files using the @load directive

== Functions

Can declare functions, cannot be nested. Can do string concatenation with the `+` symbol.

== Variables

.Scopes
* `local` - scope is restricted to the body of a function, will be assigned its initial value each time the function body is executed
* `global` 

When an error is encountered in a Bro script, it will then print out an error message with where the error is encountered.

== Primitive Datatypes

static type system - the type of data a variable holds is fixed

REs use `flex's` syntax

Domain specific types - `time`, `interval`, `port`, `addr`, `subnet`

== Operators

Many basic operators are present in Bro

== For Loops

foreach style of loop.

Vectors guarantee that the loop will take place in the expected order.

== Event Queue

https://www.bro.org/sphinx-git/scripting/index.html#the-event-queue-and-event-handlers

A key aspect of Bro scripting is handling events that are generated when Bro parses data.

Majority of events generated by Bro are defined in a built in functions


== Events

Scheduled to execute

Cannot return any value

== Hooks

Execute immediately when invoked

Allow to provide customization points for modules

Hooks can assign a `&priority` to run hooks or not run them, if a `break` is encountered, then the next hooks will not run

== Set

collection of unique values

use `add` and `delete` operators, and the `in` operator to test membership.

----
local x: set[string] = { "one", "two", "three" }

add x["four"];
----

== Table

associative collection that maps a set of unique indices to other values.

`delete` removes elements.

adding elements is done by assigning to an index.

== Vector

collection of values with 0-based indexing.

allowed to store the same value twice

== Record

user defined collection of named value of heterogeneous types - like a struct in C

use the `$` to dereference
